/* tslint:disable */
require("./UsefulLinksHP.module.css");
var styles = {
    commandBarWrapper: 'commandBarWrapper_1f4faba1',
    itmArticles: 'itmArticles_1f4faba1',
    container: 'container_1f4faba1',
    row: 'row_1f4faba1',
    column: 'column_1f4faba1',
    'ms-Grid': 'ms-Grid_1f4faba1',
    title: 'title_1f4faba1',
    subTitle: 'subTitle_1f4faba1',
    description: 'description_1f4faba1',
    button: 'button_1f4faba1',
    label: 'label_1f4faba1',
    backButtonWrapper: 'backButtonWrapper_1f4faba1',
    backButton: 'backButton_1f4faba1',
    backButtonText: 'backButtonText_1f4faba1',
    iconClass: 'iconClass_1f4faba1',
    Searchbutton: 'Searchbutton_1f4faba1',
    monjuTitle: 'monjuTitle_1f4faba1',
    customSubLogo: 'customSubLogo_1f4faba1',
    controlWrapper: 'controlWrapper_1f4faba1',
    inputWrapper: 'inputWrapper_1f4faba1',
    'ms-DetailsHeader-cellName': 'ms-DetailsHeader-cellName_1f4faba1',
    TableHeader: 'TableHeader_1f4faba1',
    modalWrapper: 'modalWrapper_1f4faba1',
    modalWrapperSub: 'modalWrapperSub_1f4faba1',
    'ms-Dialog-main': 'ms-Dialog-main_1f4faba1',
    'ms-Modal-scrollableContent': 'ms-Modal-scrollableContent_1f4faba1',
    UsefulLinksUIFabric: 'UsefulLinksUIFabric_1f4faba1',
    pageTitle: 'pageTitle_1f4faba1',
    'ms-Grid-col': 'ms-Grid-col_1f4faba1',
    formLabel: 'formLabel_1f4faba1',
    formLabelMain: 'formLabelMain_1f4faba1',
    customInputStyle: 'customInputStyle_1f4faba1',
    formGroup: 'formGroup_1f4faba1',
    referenceHeading: 'referenceHeading_1f4faba1',
    'ms-backgroundImage': 'ms-backgroundImage_1f4faba1',
    DeltaPageStatusBar: 'DeltaPageStatusBar_1f4faba1',
    'ms-designer-ribbon': 'ms-designer-ribbon_1f4faba1',
    suiteBar: 'suiteBar_1f4faba1',
    suiteBarDelta: 'suiteBarDelta_1f4faba1',
    's4-ribbonrow': 's4-ribbonrow_1f4faba1',
    's4-titlerow': 's4-titlerow_1f4faba1',
    lblNewForm: 'lblNewForm_1f4faba1',
    txtboxInput: 'txtboxInput_1f4faba1',
    txtAreaInput: 'txtAreaInput_1f4faba1',
    'section-divider': 'section-divider_1f4faba1',
    demoform: 'demoform_1f4faba1',
    attachedDoc: 'attachedDoc_1f4faba1',
    iconBlk: 'iconBlk_1f4faba1',
    'shadow-sm': 'shadow-sm_1f4faba1',
    formHeader: 'formHeader_1f4faba1',
    btn: 'btn_1f4faba1',
    'btn-cancel': 'btn-cancel_1f4faba1',
    btnSection: 'btnSection_1f4faba1',
    'btn-save': 'btn-save_1f4faba1',
    'btn-publish': 'btn-publish_1f4faba1'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=UsefulLinksHP.module.scss.js.map